# Generated by Django 3.1.6 on 2021-02-23 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenRegist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
