# Generated by Django 3.1.6 on 2021-02-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenRegist', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
