# Generated by Django 3.1.6 on 2021-02-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenRegist', '0004_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
