# Generated by Django 3.1.7 on 2021-04-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenRegist', '0005_auto_20210224_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_image'),
        ),
    ]
