# Generated by Django 3.1.7 on 2021-04-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenRegist', '0007_auto_20210403_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image', verbose_name='image'),
        ),
    ]
