# Generated by Django 3.2 on 2021-04-09 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenRegist', '0008_auto_20210403_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='manager',
        ),
    ]
